### DecarbFin step-by-step

- **Funds Overview:** Check the Description of a Fund: Horizon Europe

- **Projects:** Check a funded Project’s website: BioSFera project

- **Search My Funds:** Search for the available Funds with the criteria 'France' and 'ANSP’ – Refine the search with the criteria ‘Active Calls’

- **Calls Overview:** Check all calls attached to a given Fund: Connecting Europe Facility

- **Search My financing:** Search for Sustainable finance instruments: Sustainability-linked Loans

- **Find a Use Case:** Check for past use cases/ transactions: Air France-KLM Sustainability-linked Loan

- **Dashboard:** Become aware on latest sustainable finance trends & metrics

- **Bluebook:** Download the Bluebook

---

### The advantages of your journey

1.  Quickly identify EU funding options that are relevant for your projects, with initial guidance to apply, with Fund Pathfinder.

2.  Check success stories of past and ongoing, aviation sustainability-related, EU funded projects, as a source of inspiration.

3.  With the Bluebook, better understand the EU Taxonomy and CSRD with aviation-specific insights to help you comply with these regulations.

4.  Build a robust sustainability business case with the right EU fund(s), private financing instrument(s), and complement it with essential ESG frameworks and sustainability roadmaps.
